import { Inter } from "next/font/google";
import "./globals.css";
import GameContext from "./context/game-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GameContext>{children}</GameContext>
      </body>
    </html>
  );
}